/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout/route'
import { Route as PathlessLayoutIndexImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutViewRecordingImport } from './routes/_pathlessLayout/view-recording'
import { Route as PathlessLayoutNewRecordingImport } from './routes/_pathlessLayout/new-recording'
import { Route as PathlessLayoutCreateImport } from './routes/_pathlessLayout/create'

// Create/Update Routes

const PathlessLayoutRouteRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutIndexRoute = PathlessLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutViewRecordingRoute =
  PathlessLayoutViewRecordingImport.update({
    id: '/view-recording',
    path: '/view-recording',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutNewRecordingRoute = PathlessLayoutNewRecordingImport.update(
  {
    id: '/new-recording',
    path: '/new-recording',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any,
)

const PathlessLayoutCreateRoute = PathlessLayoutCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout/create': {
      id: '/_pathlessLayout/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof PathlessLayoutCreateImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/new-recording': {
      id: '/_pathlessLayout/new-recording'
      path: '/new-recording'
      fullPath: '/new-recording'
      preLoaderRoute: typeof PathlessLayoutNewRecordingImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/view-recording': {
      id: '/_pathlessLayout/view-recording'
      path: '/view-recording'
      fullPath: '/view-recording'
      preLoaderRoute: typeof PathlessLayoutViewRecordingImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutCreateRoute: typeof PathlessLayoutCreateRoute
  PathlessLayoutNewRecordingRoute: typeof PathlessLayoutNewRecordingRoute
  PathlessLayoutViewRecordingRoute: typeof PathlessLayoutViewRecordingRoute
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutCreateRoute: PathlessLayoutCreateRoute,
  PathlessLayoutNewRecordingRoute: PathlessLayoutNewRecordingRoute,
  PathlessLayoutViewRecordingRoute: PathlessLayoutViewRecordingRoute,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PathlessLayoutRouteRouteWithChildren
  '/create': typeof PathlessLayoutCreateRoute
  '/new-recording': typeof PathlessLayoutNewRecordingRoute
  '/view-recording': typeof PathlessLayoutViewRecordingRoute
  '/': typeof PathlessLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/create': typeof PathlessLayoutCreateRoute
  '/new-recording': typeof PathlessLayoutNewRecordingRoute
  '/view-recording': typeof PathlessLayoutViewRecordingRoute
  '/': typeof PathlessLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/_pathlessLayout/create': typeof PathlessLayoutCreateRoute
  '/_pathlessLayout/new-recording': typeof PathlessLayoutNewRecordingRoute
  '/_pathlessLayout/view-recording': typeof PathlessLayoutViewRecordingRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/create' | '/new-recording' | '/view-recording' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/create' | '/new-recording' | '/view-recording' | '/'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/_pathlessLayout/create'
    | '/_pathlessLayout/new-recording'
    | '/_pathlessLayout/view-recording'
    | '/_pathlessLayout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_pathlessLayout"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout/route.tsx",
      "children": [
        "/_pathlessLayout/create",
        "/_pathlessLayout/new-recording",
        "/_pathlessLayout/view-recording",
        "/_pathlessLayout/"
      ]
    },
    "/_pathlessLayout/create": {
      "filePath": "_pathlessLayout/create.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/new-recording": {
      "filePath": "_pathlessLayout/new-recording.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/view-recording": {
      "filePath": "_pathlessLayout/view-recording.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/": {
      "filePath": "_pathlessLayout/index.tsx",
      "parent": "/_pathlessLayout"
    }
  }
}
ROUTE_MANIFEST_END */
